# ==========================================
# CONEXIÓN A MYSQL EN AIVEN
# ==========================================

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# JPA (SIN DIALECTO)
# ==========================================

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# ==========================================
# JWT
# ==========================================

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}